[project]
name = "gdal-mcp"
version = "0.1.0"
description = "GDAL MCP Server - Expose GDAL operations as MCP tools for AI agents"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.14.0",
]

[project.scripts]
gdal-mcp-server = "server:run_server"
