[project]
name = "gdal-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gdal>=3.11.4",
    "mcp[cli]>=1.14.0",
]

[project.scripts]
gdal-mcp-server = "server:run_server"
